using Findra;
using SkiaSharp;
using Xunit;

/// <summary>
/// The face the product draws with, and the licence that has to travel with it.
///
/// <para>Spec §7 asks for Quicksand throughout; spec §9a asks for README screenshots that are the
/// product rather than a mockup, regenerated by running a command. The second is what makes the
/// first load-bearing: a surface drawn with whatever face the machine resolves cannot be
/// screenshotted reproducibly, and nothing about the image says so.</para>
/// </summary>
public class TypefaceTests
{
    [Fact]
    public void TheFaceTheProductDrawsWithIsTheOneItShips()
    {
        // The test this task exists for. If the resource is missing, misnamed, or excluded from
        // the assembly, Parts.Face falls back to the system default - correctly, because a missing
        // font must never stop the application starting - and every surface silently draws in
        // Segoe UI or whatever else the host offers. That failure has no symptom except that two
        // people's screenshots do not match.
        Assert.Equal("Quicksand", Parts.Face.FamilyName);
    }

    [Fact]
    public void TheFaceIsResolvedOnceRatherThanPerCall()
    {
        // A property that calls SKTypeface.FromStream on every access allocates a typeface per
        // access - and the settings window repaints on every pointer move, measuring several
        // labels per repaint. Assert.Same fails for a per-call implementation because each call
        // returns a new object; it passes only for a field resolved once.
        Assert.Same(Parts.Face, Parts.Face);
    }

    [Fact]
    public void TheFontIsInTheAssemblyUnderTheNameTheResolverAsksFor()
    {
        // Separate from the test above, because a rename in the csproj and a rename in Parts.cs
        // are two edits and only one of them has to be forgotten. This names the resource; the
        // first test names the consequence.
        using Stream? s = typeof(Parts).Assembly.GetManifestResourceStream("Findra.Quicksand-Regular.ttf");
        Assert.NotNull(s);
        // A subset would be a fraction of this. The floor is not a licence check - OFL condition
        // 3 is a rule this test cannot enforce - but a font that suddenly halved in size is a
        // modification somebody made, and a Modified Version may not keep the Reserved Font Name.
        Assert.True(s!.Length > 40_000, $"the embedded font is only {s.Length} bytes");
    }

    [Fact]
    public void AMissingOrUnreadableFontFallsBackInsteadOfStoppingTheApplication()
    {
        // Spec §12's habit throughout this product: a missing optional thing is a normal state.
        // A font that fails to load must not throw out of a static initialiser, which would take
        // the whole application down at the first surface that measured a string.
        Assert.Same(SKTypeface.Default, Parts.Resolve(null));

        using var rubbish = new MemoryStream([1, 2, 3, 4, 5, 6, 7, 8]);
        Assert.Same(SKTypeface.Default, Parts.Resolve(rubbish));
    }

    [Fact]
    public void TheLicenceTravelsWithTheFont()
    {
        // OFL condition 2: the font may be bundled and redistributed with any software "provided
        // that each copy contains the above copyright notice and this license". Embedding the
        // font and forgetting the licence is the breach, and it is the easy half to forget
        // because nothing stops building.
        string ofl = Repo.Read("assets/fonts/OFL.txt");
        Assert.Contains("SIL OPEN FONT LICENSE", ofl, StringComparison.OrdinalIgnoreCase);
        // The copyright line as the current release actually writes it. The upstream file names
        // "The Quicksand Project Authors" and carries the author's name only inside the project
        // URL, so this matches case-insensitively on the surname rather than on a formatting of
        // it that no shipped copy of the licence contains. The file is verbatim upstream and may
        // not be edited to suit an assertion.
        Assert.Contains("paglinawan", ofl, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("Reserved Font Name", ofl, StringComparison.Ordinal);

        // And it has to reach the machine, not merely the repository: "each copy". The csproj
        // copies it beside the executable, so the publish folder and therefore the installer
        // carry it.
        string proj = Repo.Read("src/Findra/Findra.csproj");
        Assert.Contains("OFL.txt", proj, StringComparison.Ordinal);
        Assert.Contains("CopyToOutputDirectory", proj, StringComparison.Ordinal);

        // NOTICE is what Apache-2.0 makes travel with every redistribution, so it is where a
        // reader finds out the font is under a different licence from the code.
        string notice = Repo.Read("NOTICE");
        Assert.Contains("Quicksand", notice, StringComparison.Ordinal);
        Assert.Contains("SIL Open Font License", notice, StringComparison.Ordinal);
    }

    [Fact]
    public void TheNoticeAndTheLicenceReachTheMachineAndNotJustTheRepository()
    {
        // Apache-2.0 section 4(d) requires the NOTICE to travel with every distribution, and the
        // reason this project chose Apache over MIT is that NOTICE is the mechanism carrying the
        // attribution forward. For a long time neither file reached an installed copy: the
        // installer's only [Files] entry copies the publish folder, the publish folder held one
        // licence and it was the font's, and the script's LicenseFile line merely DISPLAYS the
        // licence in the wizard rather than putting a copy on the disk. Nothing failed, nothing
        // warned, and every installed Findra shipped without the file its licence turns on.
        //
        // Asserted against the csproj rather than against a publish folder, because a publish
        // folder is not present in a fresh clone and a test that quietly skips is worse than none.
        string proj = Repo.Read("src/Findra/Findra.csproj");

        foreach (string file in new[] { "LICENSE", "NOTICE" })
        {
            // \s* spans the line ending, so no normalising is needed and none is done: a
            // Replace here would be a second thing to get right for no gain.
            Assert.Matches($@"<None\s+Include=""[^""]*{file}""[^>]*>\s*<CopyToOutputDirectory>", proj);
        }

        // And they have to say what they are, so a copy rule pointed at an empty file is caught.
        Assert.Contains("Apache License", Repo.Read("LICENSE"), StringComparison.Ordinal);
        Assert.Contains("blakazulu", Repo.Read("NOTICE"), StringComparison.OrdinalIgnoreCase);
        Assert.Contains("github.com/blakazulu/findra", Repo.Read("NOTICE"), StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void OnlyOnePlaceInTheTreeResolvesATypeface()
    {
        // The drift this catches: a new surface written later that says SKTypeface.Default because
        // that is what the surface beside it used to say. Four files did exactly that before this
        // task - the card window, the capsule window, the shot command and the self-check that
        // composes the card to measure its contrast - and the result was a product whose face
        // depended on the machine, with a comment in SearchShot claiming the real one had already
        // arrived. The self-check is the one that shows why this is a scan and not a checklist:
        // nobody thinks of a diagnostic as a surface, and it draws text all the same.
        //
        // CardText.FaceFor is not a second resolver and is deliberately not caught here: it asks
        // SKFontManager for a face that can draw one CODEPOINT the primary face lacks, which is
        // how "·" and Hebrew get drawn at all. That fallback chain stays exactly as it is.
        foreach (string file in Directory.GetFiles(Repo.Path_("src/Findra"), "*.cs", SearchOption.AllDirectories))
        {
            if (file.Contains(Path.DirectorySeparatorChar + "obj" + Path.DirectorySeparatorChar, StringComparison.Ordinal)) continue;
            if (Path.GetFileName(file) == "Parts.cs") continue;

            Assert.DoesNotContain("SKTypeface.Default", File.ReadAllText(file), StringComparison.Ordinal);
        }
    }
}
