using System.Linq;

using Findra.Startup;   // HelperTaskState, for the settings shot
using SkiaSharp;

namespace Findra.Diagnostics;

/// <summary>
/// `--searchshot`: any surface, in any palette, rendered to a PNG with no window and no screen.
/// Findra's card renders entirely offscreen, so this is not a debugging aid bolted on afterward -
/// it is how every state the capsule and card can be in gets built and reviewed. It must learn
/// each new palette and each new surface as they are written.
///
/// With no palette argument, every state (not only `capsule`) is shot in the SAME palette the
/// running app would actually resolve - <see cref="Theme.Resolve"/> over the on-disk config,
/// the live Windows light/dark setting and the on-disk palette set - so the default shot is the
/// look someone actually has, not a fixed built-in that could quietly drift from it. An explicit
/// palette argument always wins over that default.
/// </summary>
public static class SearchShot
{
    public static readonly IReadOnlyList<string> States =
    [
        "capsule", "empty", "indexing", "contentmode", "contentwaiting", "typing", "results",
        "noresults", "many", "adv", "opening", "openingempty",
        "settings", "settingsopening", "settingssearches", "settingscontent", "settingsabout",
        "firstrun", "firstruninstalled", "firstrunspeech", "firstrundownloading", "firstrunfinished",
        "firstrunready",
    ];

    public static int Render(string outPath, string state, string? paletteName = null)
    {
        state = state.Trim().ToLowerInvariant();
        if (!States.Contains(state))
        {
            Console.Error.WriteLine($"searchshot: unknown state '{state}'");
            Console.Error.WriteLine("  states: " + string.Join(", ", States));
            return 1;
        }

        Palette palette;
        if (paletteName is null)
        {
            // No argument: the configured palette, exactly as the running app would resolve it.
            palette = Theme.Resolve(Config.LoadFromDisk(), Theme.WindowsIsLight(), PaletteStore.LoadFromDisk());
        }
        else
        {
            // Palette.ByName resolves against the palettes loaded from disk, not just the
            // built-ins, so a shot of a hand-written palette is possible - the same reasoning as
            // the self-test's legibility check.
            Palette? found = Palette.ByName(paletteName);
            if (found is null)
            {
                Console.Error.WriteLine($"searchshot: unknown palette '{paletteName}'");
                Console.Error.WriteLine("  palettes: " +
                    string.Join(", ", PaletteStore.LoadFromDisk().Select(p => p.Name)));
                return 1;
            }
            palette = found;
        }

        Derived d = Derived.From(palette);
        // The shipped face, not the platform's. Every image in the README is regenerated by this
        // command (spec §9a), so a shot that drew in whatever face the machine resolved would not
        // reproduce on anybody else's - which is the difference between a screenshot and a
        // mockup. Parts.Face falls back to the default on its own if the resource is missing.
        SKTypeface face = Parts.Face;

        using SKBitmap content =
            state == "capsule" ? RenderCapsule(d, face)
            : state.StartsWith("settings", StringComparison.Ordinal) ? RenderSettings(state, d, face)
            : state.StartsWith("firstrun", StringComparison.Ordinal) ? RenderFirstRun(state, d, face)
            : RenderCard(state, d, face);

        int w = content.Width, h = content.Height;
        var info = new SKImageInfo(w, h, SKColorType.Bgra8888, SKAlphaType.Premul);
        using SKSurface surface = SKSurface.Create(info);
        SKCanvas c = surface.Canvas;

        // A checkerboard so a transparent corner shows up in the PNG itself rather than only in
        // an alpha channel nobody opens a viewer to inspect. Its two squares are close to the
        // palette's own ground, so a light palette is not reviewed sitting on a board built for
        // a dark one.
        SKColor toward = palette.Light ? SKColors.Black : SKColors.White;
        SKColor square1 = Derived.Mix(palette.Ground, toward, 0.05f);
        SKColor square2 = Derived.Mix(palette.Ground, toward, 0.11f);
        using (var bg = new SKPaint { Color = square1 }) c.DrawRect(0, 0, w, h, bg);
        using (var sq = new SKPaint { Color = square2 })
            for (int yy = 0; yy < h; yy += 24)
                for (int xx = ((yy / 24) % 2) * 24; xx < w; xx += 48)
                    c.DrawRect(xx, yy, 24, 24, sq);

        c.DrawBitmap(content, 0, 0);
        c.Flush();

        try
        {
            using SKImage image = surface.Snapshot();
            using SKData data = image.Encode(SKEncodedImageFormat.Png, 100);
            using FileStream fs = File.Open(Path.GetFullPath(outPath), FileMode.Create);
            data.SaveTo(fs);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"searchshot: could not write '{outPath}': {ex.Message}");
            return 2;
        }

        Console.WriteLine($"searchshot: '{state}' in {palette.Name}, {w}x{h} -> {Path.GetFullPath(outPath)}");
        return 0;
    }

    private static SKBitmap RenderCapsule(Derived d, SKTypeface face)
    {
        var info = new SKImageInfo((int)CapsuleLayout.Width, (int)CapsuleLayout.Height,
                                   SKColorType.Bgra8888, SKAlphaType.Premul);
        using SKSurface surface = SKSurface.Create(info);
        // The pill as the product composes it, through IndexStatus.Pill rather than three literals:
        // a shot that made up its own label and count would be the second copy this file has
        // already been caught keeping.
        CapsulePainter.Paint(surface.Canvas, CapsulePainter.Placeholder,
                             IndexStatus.Pill(contentEnabled: true, kind: "Photo",
                                              pending: 4_120, indexed: 6_680, alive: true),
                             d, face);
        surface.Canvas.Flush();
        var bmp = new SKBitmap(info);
        surface.ReadPixels(info, bmp.GetPixels(), info.RowBytes, 0, 0);
        return bmp;
    }

    private static SKBitmap RenderSettings(string state, Derived d, SKTypeface face)
    {
        Section section = state switch
        {
            "settingsopening" => Section.Opening,
            "settingssearches" => Section.Searches,
            "settingscontent" => Section.Content,
            "settingsabout" => Section.About,
            _ => Section.Look,
        };

        var config = Config.Default with
        {
            DarkPalette = "Brass", LightPalette = "Blueprint", Hotkey = "Alt+Space",
            IndexContent = true, TranscribeMinutes = 30, InstallSource = "winget",
            IndexDrives = ["C"], SearchExclusions = [.. FileKinds.DefaultExclusions],
        };

        var s = new SettingsState(config)
        {
            Section = section,
            Palettes = PaletteStore.LoadFromDisk(),        // once, here, not per swatch per frame
            Drives = ["C", "D", "E"],
            HebrewOffered = true,
            Helper = section == Section.Opening ? HelperTaskState.Unknown : HelperTaskState.Registered,
            // The rebind message is a shot state for its own reason: spec 7 insists it must never
            // be silent, and no unit test looks at pixels.
            HotkeyMessage = section == Section.Opening
                ? "Ctrl+Shift+P is taken by something else. Findra kept Alt+Space." : "",
            EverIndexed = true, IndexerAlive = true,
            // Scrolled, because the exclusions list is the only scroller in the product and an
            // unscrolled list never shows what a partial page looks like.
            ExclusionScroll = section == Section.Searches ? 6 : 0,
            Installed = new CapabilitySet(new HashSet<Capability> { Capability.Meaning }),
            Version = BuildInfo.Version, Update = UpdateState.Available, Latest = "1.4.0",
            HoverTarget = PanelTarget.Section, HoverRow = 1,
        };

        int w = (int)Math.Ceiling(RailLayout.Width), h = (int)Math.Ceiling(RailLayout.Height);
        var info = new SKImageInfo(w, h, SKColorType.Bgra8888, SKAlphaType.Premul);
        using SKSurface surface = SKSurface.Create(info);
        SettingsPainter.Paint(surface.Canvas, s, d, face);
        surface.Canvas.Flush();
        var bmp = new SKBitmap(info);
        surface.ReadPixels(info, bmp.GetPixels(), info.RowBytes, 0, 0);
        return bmp;
    }

    /// <summary>
    /// Spec §6's first screen, in all four of the shapes it takes.
    ///
    /// <para>Built on the REAL numbers - every size comes through <c>FirstRun.Rows</c> and the
    /// summary through <c>FirstRun.Summary</c>, so a shot of this screen cannot quote a figure the
    /// product would not. The downloading state carries one capability finished, one part-way AND
    /// a problem, because those are the three things the second act can be showing and none of
    /// them has a unit test that looks at pixels.</para>
    ///
    /// <para><c>firstrunspeech</c> is a state of its own rather than a variation of the first,
    /// because the transcription limit is only on the screen when Speech is taken and the two
    /// layouts are what a review has to compare: the row appears between Speech and the Hebrew
    /// pass, and everything below it moves down by a band.</para>
    ///
    /// <para><c>firstrunfinished</c> is a state of its own for the same kind of reason, and it is
    /// the one that was missing. The end of a run is a painter branch nobody had ever rendered:
    /// its own title, its own sentence, no problem to report, and both bars full - which is
    /// exactly the arm a defect hid in, because a download that could never finish was reported
    /// by nothing anybody looked at.</para>
    /// </summary>
    private static SKBitmap RenderFirstRun(string state, Derived d, SKTypeface face)
    {
        // Two finished screens, because the last act has two shapes and one state can only ever
        // show one of them. `firstrunfinished` took reading, so it carries the last question and
        // two buttons; `firstrunready` did not, so it is the plain "Findra is ready" with one way
        // out. A finished shot that only ever had reading on would ship the other half of the
        // painter unlooked at, which is the rule the card's picture branch is written under.
        bool ready = state == "firstrunready";
        bool done = state == "firstrunfinished" || ready;
        bool busy = state == "firstrundownloading" || done;
        bool speech = state == "firstrunspeech";
        // A reinstall over kept models, which is what an uninstall leaves behind unless the purge
        // box was ticked. Every row says "installed", every tile costs 0 MB and the summary is a
        // sentence rather than a number - a branch of this painter that no other state reaches,
        // and the one this screen was wrong about for its whole life.
        bool installed = state == "firstruninstalled";
        var s = new FirstRunState
        {
            // The installed shot ticks what it has, exactly as the product does - a row reading
            // "installed" beside an empty tick box is a state the shell cannot produce, and a shot
            // of it would be reviewing something that does not exist.
            Chosen = installed
                ? FirstRun.AlreadyChosen(
                    new HashSet<string>(ModelStore.All.Select(m => m.File), StringComparer.OrdinalIgnoreCase),
                    hebrewOffered: true)
                : speech
                ? Capabilities.Close([Capability.Photos, Capability.Speech])
                : Capabilities.Close([Capability.Photos, Capability.Meaning]),
            HebrewOffered = true,
            ContentOn = !ready,
            OnDisk = installed
                ? new HashSet<string>(ModelStore.All.Select(m => m.File), StringComparer.OrdinalIgnoreCase)
                : new HashSet<string>(StringComparer.OrdinalIgnoreCase),
            CheckUpdates = true,
            StartAtLogon = true,
            // Not the default, so the shot shows a chosen pill somewhere other than where an
            // untouched screen would put it - and shows that the control is answered rather than
            // decorative.
            TranscribeMinutes = speech ? 30 : TranscribeLimit.Default,
            Stage = done ? FirstRunStage.Finished
                  : busy ? FirstRunStage.Downloading
                  : FirstRunStage.Choosing,
            Downloads = done
                ?
                [
                    new CapabilityProgress(Capability.Photos, 659_000_000, 659_000_000),
                    new CapabilityProgress(Capability.Meaning, 283_000_000, 283_000_000),
                ]
                : busy
                ?
                [
                    new CapabilityProgress(Capability.Photos, 659_000_000, 659_000_000),
                    new CapabilityProgress(Capability.Meaning, 96_000_000, 283_000_000),
                ]
                : [],
            // The finished shot carries no problem, because "everything arrived" is the arm the
            // summary has to be able to reach and a run with a fault never reaches it.
            Problem = busy && !done ? "the connection dropped" : "",
            // Hovered, because a resting surface never shows what RowHover looks like beside Row -
            // the defect that let hover sit within 1.4 L* of a resting row on two palettes. The
            // speech state hovers a limit pill that is not the chosen one, which is the only place
            // a pill's hover fill is painted on this screen at all.
            // In the second act the way out is the only thing that answers a pointer at all, so
            // it is the only thing a hover can be on. "Not now" is not drawn there.
            HoverTarget = busy ? FirstRunTarget.Go : speech ? FirstRunTarget.Limit : FirstRunTarget.Row,
            // 3 is the Hebrew row on the choosing screen and the "2 hr" pill on the speech one -
            // in both cases something other than what is already chosen.
            HoverIndex = busy ? -1 : 3,
        };

        // The second act is a shorter window than the first, and the shot has to be the size the
        // window really is or the review render carries an empty band the product does not have.
        int rows = FirstRun.Rows(s).Count;
        int limitRow = FirstRun.LimitRow(s);
        float tall = busy
            ? FirstRunLayout.SettledHeight(rows, limitRow, FirstRun.Asks(s))
            : FirstRunLayout.Height;

        int w = (int)Math.Ceiling(FirstRunLayout.Width), h = (int)Math.Ceiling(tall);
        var info = new SKImageInfo(w, h, SKColorType.Bgra8888, SKAlphaType.Premul);
        using SKSurface surface = SKSurface.Create(info);
        FirstRunPainter.Paint(surface.Canvas, s, d, face);
        surface.Canvas.Flush();
        var bmp = new SKBitmap(info);
        surface.ReadPixels(info, bmp.GetPixels(), info.RowBytes, 0, 0);
        return bmp;
    }

    private static SKBitmap RenderCard(string state, Derived d, SKTypeface face)
    {
        SearchCardState s = Build(state);
        int w = (int)Math.Ceiling(SearchCardLayout.Width);
        int h = (int)Math.Ceiling(SearchCardLayout.Height(s.Rows.Count, s.HasQuery, s.AdvOpen, s.Progress.Show));
        var info = new SKImageInfo(w, h, SKColorType.Bgra8888, SKAlphaType.Premul);
        using SKSurface surface = SKSurface.Create(info);
        SearchCardPainter.Paint(surface.Canvas, s, d, face);
        surface.Canvas.Flush();
        var bmp = new SKBitmap(info);
        surface.ReadPixels(info, bmp.GetPixels(), info.RowBytes, 0, 0);
        return bmp;
    }

    // A fixed, fake result set per state - no query engine, no admin rights, no index. This is
    // what lets every state in every palette be reviewed on a machine that has never indexed
    // anything.
    /// <summary>The worst case the footer has to survive: both halves of the index line at their
    /// longest reachable state. <c>CardFooterTests</c> measures this same pair of sentences.
    /// </summary>
    private const string LongIndexLine =
        "1.5M names on C:, D:, E: (helper pid 12345) (still reading the drive) · " +
        "1,234,567 waiting - indexing is paused while Findra is closed";

    private static SearchCardState Build(string state)
    {
        if (state == "empty")
            return SearchCardState.Empty with { IndexLine = "index: 1.5M names · idle", Clock = 0.2 };

        // The card in content mode with nothing typed, which is two branches nothing else reached.
        //
        // The field's content placeholder is one: it is a DIFFERENT string from the name-mode one -
        // the pill changes what a query means, so a field promising the same thing in both modes
        // would be the pill's only invisible effect - and the field ellipsises, so an overlong one
        // is not a crash or a clipped glyph but a sentence that stops mid-thought. It had been
        // doing exactly that, at 606.6px against 580.6px, on every empty card in content mode.
        //
        // The Content pill LATCHED is the other. Every other state leaves Content false, so the
        // one pill on this card that latches had only ever been rendered unlatched.
        // The card with the progress pill under its field, which is the state somebody opening
        // Findra during a first pass actually meets. No other state draws it, and the pill changes
        // the card's HEIGHT - so an unrendered one is a layout nothing has ever looked at.
        if (state == "indexing")
            return SearchCardState.Empty with
            {
                IndexLine = "indexing 1,030 · 688 done",
                Progress = IndexStatus.Pill(contentEnabled: true, nameof(ResultKind.Document),
                                            pending: 342, indexed: 688, alive: true),
                Clock = 0.2,
            };

        if (state == "contentmode")
            return SearchCardState.Empty with
            {
                Content = true,
                IndexLine = "index up to date · 12,480 files",
                Clock = 0.2,
            };

        // The Content pill drawn NOT offering, which is the one branch of the pill painter no
        // other state reaches: reading is on, the first pass has queued work and not finished a
        // file, so there is nothing to search, nothing to turn on and nothing settings could add.
        // A card whose every state showed a live pill would ship the faded one unlooked at - the
        // same defect as the stage's picture branch, which nine states missed between them.
        //
        // Hovered on purpose. The suppression of the hover fill is half of what makes a dead
        // control read as dead, and a state that never hovers it proves only the resting colour.
        if (state == "contentwaiting")
            return SearchCardState.Empty with
            {
                IndexLine = "reading inside your files - nothing found yet",
                ContentOffered = false,
                HoverTarget = SearchTarget.Content,
                Clock = 0.2,
            };

        // The unfold has a Restore on each of the painter's two return paths, and an unbalanced
        // canvas is exactly what that shape produces when one is missed - so both are shot. This
        // is the short one, and the one a user actually sees: clicking the capsule opens a card
        // with no query in it. `opening` below is the same animation over a full result list.
        if (state == "openingempty")
            return SearchCardState.Empty with
            {
                IndexLine = "index: 1.5M names · idle", Clock = 0.2, OpenedAt = 0.13,
            };

        if (state == "adv")
            return SearchCardState.Empty with
            {
                AdvOpen = true, AdvFocus = 0, IndexLine = "index: 1.5M names · idle", Clock = 0.2,
                AdvRules = new SearchAdvanced(AllWords: "lake cabin", NoneWords: "draft",
                    Kind: 1, SizeFrom: "1mb", DateFrom: "2026-01-01"),
                // Close hovered, so the popup's three button surfaces are all on screen at once:
                // Close takes the hover step, Apply rests one above it, and the chosen Kind chip
                // takes the top one. Nothing but a shot ever looked at these.
                HoverTarget = SearchTarget.AdvButton, HoverIndex = 1,
            };

        string query = state switch
        {
            "typing" => "sun",
            "noresults" => "zqxjkv",
            _ => "sunset",
        };

        var fake = new List<SearchResult>();
        if (state is "results" or "many" or "opening")
        {
            fake.Add(new SearchResult(ResultKind.Photo, "IMG_4471.HEIC",
                @"D:\Photos\2025\08 Crete\IMG_4471.HEIC", 0.91f, "looks like \u201csunset over water\u201d"));
            fake.Add(new SearchResult(ResultKind.Photo, "DSC_0982.jpg",
                @"D:\Photos\2024\Eilat\DSC_0982.jpg", 0.86f, "looks like \u201csunset over water\u201d"));
            fake.Add(new SearchResult(ResultKind.Video, "GX010233.MP4",
                @"D:\Video\GoPro\GX010233.MP4", 0.74f, "a moment at 2:14", 134));
            fake.Add(new SearchResult(ResultKind.Document, "Q3-revenue-review.pdf",
                @"C:\Users\rae\Documents\Finance\Q3-revenue-review.pdf", 0.66f, "says it",
                Excerpt: "…the quarterly revenue came in 12% above the plan, driven by the sunset of the legacy tier…"));
            fake.Add(new SearchResult(ResultKind.Document, "הסכם-שכירות-2026.docx",
                @"C:\Users\rae\Documents\הסכם-שכירות-2026.docx", 0.62f, "says it",
                Excerpt: "השוכר מתחייב לפנות את הדירה עד סוף אוגוסט, ולהשיב את המפתחות"));
            fake.Add(new SearchResult(ResultKind.Audio, "Voice 014.m4a",
                @"C:\Users\rae\Music\Voice Memos\Voice 014.m4a", 0.58f, "spoken at 1:07", 67,
                Excerpt: "\u201c…we said sunset, like eight-thirty, and bring the tripod…\u201d"));
            fake.Add(new SearchResult(ResultKind.File, "sunset-preset.lrtemplate",
                @"C:\Users\rae\AppData\Roaming\Adobe\Lightroom\sunset-preset.lrtemplate", 0.90f, "name starts with it"));
            fake.Add(new SearchResult(ResultKind.File, "sunset_over_water.txt",
                @"C:\Users\rae\Documents\notes\sunset_over_water.txt", 0.90f, "name starts with it"));
            fake.Add(new SearchResult(ResultKind.Folder, "Sunsets",
                @"D:\Photos\Collections\Sunsets", 1.0f, "exact name"));
            if (state == "many")
                for (int i = 0; i < 14; i++)
                    fake.Add(new SearchResult(ResultKind.File, $"sunset-{i:00}.txt",
                        $@"C:\Users\rae\Documents\notes\sunset-{i:00}.txt", 0.68f, "name"));
        }

        var results = new SearchResults(query, fake, 2.4, 0, false);
        IReadOnlyList<SearchResult> rows = SearchCardState.Filtered(results, 0);
        // `many` scrolls three rows down, so its highlight has to move with the window - at 0 the
        // one shot with enough rows to be worth looking at showed no selection at all.
        int scroll = state == "many" ? 3 : 0;
        int highlight = scroll + (state == "many" ? 1 : 0);
        return new SearchCardState(query, results, rows, 0, highlight, scroll, state == "typing",
            Caret: query.Length,
            // `many` carries the LONGEST index line the card can be handed: three drives, the
            // helper still reading, and a backlog left by a previous session, with the content
            // half joined on the way CardWindow joins it. The footer's two halves share one row,
            // and until this line existed no shot showed them under any pressure at all - which
            // is how a 7.6 px overlap in the ORDINARY single-drive state went unseen. Every
            // clause here is a sentence IndexStatus.Line or IndexLineFormatter really produces.
            IndexLine: state == "many" ? LongIndexLine : "index: 1.5M names · idle",
            StageDetail: "3.1 MB · 12 Aug 2026 19:42", Clock: 0.2,
            // The stage's PICTURE branch - the centre-crop in DrawStage - was painted by no shot
            // at all: every state left StageImage null and took the no-art tile, so the one
            // surface whose whole job is showing you the file was only ever reviewed in its
            // fallback. `results` and `opening` highlight a photo and get one; `many` highlights
            // a document and keeps the tile, so both branches are on screen somewhere.
            StageImage: highlight >= 0 && highlight < rows.Count && rows[highlight].Kind == ResultKind.Photo
                ? SunsetOverWater() : null,
            // `results` hovers a row that is not the selected one: without it the list's hover
            // fill is painted by no shot and no test, which is what let RowHover sit within
            // 1.4 L* of Row - and inverted on two palettes - without anything noticing.
            HoverTarget: state == "results" ? SearchTarget.Row : SearchTarget.None,
            HoverIndex: state == "results" ? 2 : -1,
            // `opening` catches the card mid-unfold with a full list, a third of the way through
            // the 220 ms: the painter takes its SaveLayer + ClipRect branch and has to balance the
            // canvas on the long return path. `openingempty` above covers the early one.
            OpenedAt: state == "opening" ? 0.13 : -1);
    }

    /// <summary>The demo photograph: a sunset over water, DRAWN rather than photographed.
    ///
    /// <para>Everything else about this state is invented too - the file names, the drive
    /// letters, the scores, the Hebrew tenancy agreement - and the point of the shot has never
    /// been that the data is real. It is that the PAINTER is: what a shot shows is what the card
    /// puts on a screen, pixel for pixel. So the picture is handed to <c>DrawStage</c> as an
    /// ordinary <see cref="SKImage"/> and goes through the same clip, the same centre-crop and
    /// the same sampling a decoded HEIC would.</para>
    ///
    /// <para>It is deliberately 3:2 and not square. The stage's picture well is square for a
    /// photo, so a square source would scale and never crop, and the crop is the half of that
    /// branch most likely to be wrong. This one loses a third of its width and keeps the sun.
    /// </para></summary>
    private static SKImage SunsetOverWater()
    {
        const int w = 480, h = 320;
        const float horizon = h * 0.60f;

        using SKSurface surface = SKSurface.Create(new SKImageInfo(w, h, SKColorType.Bgra8888, SKAlphaType.Premul));
        SKCanvas c = surface.Canvas;

        using (var sky = new SKPaint { IsAntialias = true })
        {
            sky.Shader = SKShader.CreateLinearGradient(
                new SKPoint(0, 0), new SKPoint(0, horizon),
                [new SKColor(0x1B, 0x1E, 0x3C), new SKColor(0x5B, 0x35, 0x63),
                 new SKColor(0xC9, 0x5A, 0x3A), new SKColor(0xFF, 0xC1, 0x6B)],
                [0f, 0.42f, 0.78f, 1f], SKShaderTileMode.Clamp);
            c.DrawRect(new SKRect(0, 0, w, horizon), sky);
        }

        // The sun, just clear of the horizon and off centre, so the crop has something to keep.
        const float sx = w * 0.62f, sy = horizon - 24f, sr = 29f;
        using (var glow = new SKPaint { IsAntialias = true })
        {
            glow.Shader = SKShader.CreateRadialGradient(
                new SKPoint(sx, sy), sr * 3.6f,
                [new SKColor(0xFF, 0xD9, 0x8A, 150), new SKColor(0xFF, 0xD9, 0x8A, 0)],
                SKShaderTileMode.Clamp);
            c.DrawCircle(sx, sy, sr * 3.6f, glow);
        }
        using (var disc = new SKPaint { IsAntialias = true, Color = new SKColor(0xFF, 0xEC, 0xB8) })
            c.DrawCircle(sx, sy, sr, disc);

        // Blurred, because an unblurred bar in a sky reads as a user-interface element rather
        // than as cloud, and this picture has to survive being three centimetres wide.
        using (var cloud = new SKPaint
        {
            IsAntialias = true, Color = new SKColor(0x33, 0x24, 0x40, 165),
            ImageFilter = SKImageFilter.CreateBlur(7f, 3.5f),
        })
        {
            c.DrawRoundRect(new SKRoundRect(new SKRect(w * 0.02f, horizon - 100, w * 0.54f, horizon - 86), 7), cloud);
            c.DrawRoundRect(new SKRoundRect(new SKRect(w * 0.36f, horizon - 66, w * 1.00f, horizon - 55), 6), cloud);
        }

        using (var sea = new SKPaint { IsAntialias = true })
        {
            sea.Shader = SKShader.CreateLinearGradient(
                new SKPoint(0, horizon), new SKPoint(0, h),
                [new SKColor(0xD2, 0x86, 0x50), new SKColor(0x2A, 0x3E, 0x50), new SKColor(0x10, 0x19, 0x26)],
                [0f, 0.45f, 1f], SKShaderTileMode.Clamp);
            c.DrawRect(new SKRect(0, horizon, w, h), sea);
        }

        // The sun's light on the water: a soft wedge widening as it comes forward, with broken
        // streaks over it. A stack of centred bars on its own reads as a staircase, so the wedge
        // carries the glow and the streaks only break it up.
        using (var column = new SKPaint { IsAntialias = true, ImageFilter = SKImageFilter.CreateBlur(9f, 5f) })
        {
            column.Shader = SKShader.CreateLinearGradient(
                new SKPoint(0, horizon), new SKPoint(0, h),
                [new SKColor(0xFF, 0xDA, 0x8C, 190), new SKColor(0xFF, 0xC0, 0x70, 40)],
                SKShaderTileMode.Clamp);
            using var wedge = new SKPath();
            wedge.MoveTo(sx - 10f, horizon);
            wedge.LineTo(sx + 10f, horizon);
            wedge.LineTo(sx + 62f, h);
            wedge.LineTo(sx - 62f, h);
            wedge.Close();
            c.DrawPath(wedge, column);
        }

        // A fixed seed, so the same command produces the same file: a shot that differs run to
        // run cannot be checked against the one in the repository.
        uint seed = 0x5EA5;
        float Rand()
        {
            seed = seed * 1664525u + 1013904223u;
            return ((seed >> 8) & 0xFFFF) / 65535f;
        }

        // Several short pieces scattered across the column at each depth, not one centred bar
        // per row: a bar per row is a ladder, and a ladder is what the eye sees first.
        using (var streak = new SKPaint { IsAntialias = true })
            for (float y = horizon + 3f; y < h; y += 5.5f)
            {
                float t = (y - horizon) / (h - horizon);
                float reach = 8f + t * 58f;
                int pieces = 1 + (int)(Rand() * 3f);
                for (int i = 0; i < pieces; i++)
                {
                    // Two samples averaged, so the pieces crowd the middle of the column and
                    // thin out at its edges, which is where a real glitter path puts them.
                    float bias = (Rand() + Rand()) / 2f;
                    float cx = sx + (bias * 2f - 1f) * reach;
                    float len = reach * (0.16f + Rand() * 0.42f);
                    streak.Color = new SKColor(0xFF, 0xE8, 0xB6,
                        (byte)(140f * (1f - t * 0.6f) * (0.45f + Rand() * 0.55f)));
                    c.DrawRoundRect(new SKRoundRect(
                        new SKRect(cx - len / 2f, y, cx + len / 2f, y + 2.1f), 1.05f), streak);
                }
            }

        c.Flush();
        return surface.Snapshot();
    }
}
